### ISSUE TITLE
Incorrect time zone for Western Australia

### ISSUE THREAD

**Issue by alex-hhh** [97jaz/cldr-core#1]
On a Windows PC, when I try to use the `system-tzid` function from the `tzinfo` package on my PC in Western Australia, it returns "Antarctica/Casey" -- this is because the `windowsZones.json` file in this package contains an incorrect mapping of the Windows time zone name, which is "W. Australia Standard Time" to "Antarctica/Casey".

I manually updated the cldr-core.zip file with the contents of the https://github.com/unicode-cldr/cldr-core project and the issue is fixed and `system-tzid` returns "Australia/Perth" as expected.

I think this package needs to be updated to pick up the fixes that happened in the https://github.com/unicode-cldr/cldr-core project.  If you are interested, I can submit a pull request with an updated ZIP file.

Thanks,
Alex.

**Comment by 97jaz** [comment]
Hi Alex,
I think the problem isn't in this package at all (though it is certainly using old CLDR data). Rather, the problem is in `tzinfo` where I am not taking the `_territory` into account [when mapping from Windows zones to IANA zones](https://github.com/97jaz/tzinfo/blob/master/tzinfo/private/os/windows.rkt#L28).

I ought to be looking for the record where `_territory` is `001`.

**Comment by alex-hhh** [comment]
Indeed, this patch to the `tzinfo` package fixes the problem:

```diff
 tzinfo/private/os/windows.rkt | 14 ++++++++++----
 1 file changed, 10 insertions(+), 4 deletions(-)

diff --git a/tzinfo/private/os/windows.rkt b/tzinfo/private/os/windows.rkt
index 4c435ad..2c7078a 100644
--- a/tzinfo/private/os/windows.rkt
+++ b/tzinfo/private/os/windows.rkt
@@ -27,10 +27,16 @@
 
 (define (windows->tzid tz)
   (and tz
-       (for*/first ([mz (in-list (windows-zones))]
-                    [win (in-value (cldr-ref mz '(mapZone _other)))]
-                    #:when (equal? tz win))
-         (cldr-ref mz '(mapZone _type)))))
+       (or
+        ;; Look first for the "001" territory (the default)
+        (for/first ([mz (in-list (windows-zones))]
+                    #:when (and (equal? tz (cldr-ref mz '(mapZone _other)))
+                                (equal? "001" (cldr-ref mz '(mapZone _territory)))))
+          (cldr-ref mz '(mapZone _type)))
+        ;; If not found, look for any territory
+        (for/first ([mz (in-list (windows-zones))]
+                    #:when (equal? tz (cldr-ref mz '(mapZone _other))))
+          (cldr-ref mz '(mapZone _type))))))
 
 (define (tzid-from-registry-list prefix)
   (define standard (standard-name))

```

**Comment by 97jaz** [comment]
Fixed https://github.com/97jaz/tzinfo/pull/12

**Comment by alex-hhh** [comment]
I tested this with my application and this fixes the problem.  Thanks, Alex.
